services:
 redis:
  image: redis:7.2-alpine
  #  container_name: redis
  #  restart: always
  ports:
      - "6379:6379"
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 10s
    timeout: 5s
    retries: 5
  command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  volumes:
    - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    - redis_data:/data

volumes:
 redis_data:
   driver: local