// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	domain "backend/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	utils "backend/internal/utils"

	uuid "github.com/google/uuid"
)

// MockUserUsecase is an autogenerated mock type for the UserUsecase type
type MockUserUsecase struct {
	mock.Mock
}

type MockUserUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUsecase) EXPECT() *MockUserUsecase_Expecter {
	return &MockUserUsecase_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, email, password
func (_m *MockUserUsecase) Authenticate(ctx context.Context, email string, password string) (*domain.User, string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserUsecase_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockUserUsecase_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockUserUsecase_Expecter) Authenticate(ctx interface{}, email interface{}, password interface{}) *MockUserUsecase_Authenticate_Call {
	return &MockUserUsecase_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, email, password)}
}

func (_c *MockUserUsecase_Authenticate_Call) Run(run func(ctx context.Context, email string, password string)) *MockUserUsecase_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserUsecase_Authenticate_Call) Return(_a0 *domain.User, _a1 string, _a2 error) *MockUserUsecase_Authenticate_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserUsecase_Authenticate_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, string, error)) *MockUserUsecase_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserUsecase) Create(ctx context.Context, user *domain.User) (*domain.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) (*domain.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockUserUsecase_Expecter) Create(ctx interface{}, user interface{}) *MockUserUsecase_Create_Call {
	return &MockUserUsecase_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserUsecase_Create_Call) Run(run func(ctx context.Context, user *domain.User)) *MockUserUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockUserUsecase_Create_Call) Return(_a0 *domain.User, _a1 error) *MockUserUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUsecase_Create_Call) RunAndReturn(run func(context.Context, *domain.User) (*domain.User, error)) *MockUserUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserUsecase) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserUsecase_Expecter) Delete(ctx interface{}, id interface{}) *MockUserUsecase_Delete_Call {
	return &MockUserUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserUsecase_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserUsecase_Delete_Call) Return(_a0 error) *MockUserUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserUsecase_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUserUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockUserUsecase) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUsecase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserUsecase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserUsecase_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserUsecase_GetByID_Call {
	return &MockUserUsecase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserUsecase_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserUsecase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserUsecase_GetByID_Call) Return(_a0 *domain.User, _a1 error) *MockUserUsecase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUsecase_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.User, error)) *MockUserUsecase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, limit
func (_m *MockUserUsecase) List(ctx context.Context, page int, limit int) (*utils.PaginatedResponse[domain.User], error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *utils.PaginatedResponse[domain.User]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*utils.PaginatedResponse[domain.User], error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *utils.PaginatedResponse[domain.User]); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.PaginatedResponse[domain.User])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockUserUsecase_Expecter) List(ctx interface{}, page interface{}, limit interface{}) *MockUserUsecase_List_Call {
	return &MockUserUsecase_List_Call{Call: _e.mock.On("List", ctx, page, limit)}
}

func (_c *MockUserUsecase_List_Call) Run(run func(ctx context.Context, page int, limit int)) *MockUserUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockUserUsecase_List_Call) Return(_a0 *utils.PaginatedResponse[domain.User], _a1 error) *MockUserUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUsecase_List_Call) RunAndReturn(run func(context.Context, int, int) (*utils.PaginatedResponse[domain.User], error)) *MockUserUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByRole provides a mock function with given fields: ctx, role, page, limit
func (_m *MockUserUsecase) ListByRole(ctx context.Context, role domain.UserRole, page int, limit int) (*utils.PaginatedResponse[domain.User], error) {
	ret := _m.Called(ctx, role, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByRole")
	}

	var r0 *utils.PaginatedResponse[domain.User]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserRole, int, int) (*utils.PaginatedResponse[domain.User], error)); ok {
		return rf(ctx, role, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserRole, int, int) *utils.PaginatedResponse[domain.User]); ok {
		r0 = rf(ctx, role, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.PaginatedResponse[domain.User])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserRole, int, int) error); ok {
		r1 = rf(ctx, role, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUsecase_ListByRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByRole'
type MockUserUsecase_ListByRole_Call struct {
	*mock.Call
}

// ListByRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role domain.UserRole
//   - page int
//   - limit int
func (_e *MockUserUsecase_Expecter) ListByRole(ctx interface{}, role interface{}, page interface{}, limit interface{}) *MockUserUsecase_ListByRole_Call {
	return &MockUserUsecase_ListByRole_Call{Call: _e.mock.On("ListByRole", ctx, role, page, limit)}
}

func (_c *MockUserUsecase_ListByRole_Call) Run(run func(ctx context.Context, role domain.UserRole, page int, limit int)) *MockUserUsecase_ListByRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserRole), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockUserUsecase_ListByRole_Call) Return(_a0 *utils.PaginatedResponse[domain.User], _a1 error) *MockUserUsecase_ListByRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUsecase_ListByRole_Call) RunAndReturn(run func(context.Context, domain.UserRole, int, int) (*utils.PaginatedResponse[domain.User], error)) *MockUserUsecase_ListByRole_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, user
func (_m *MockUserUsecase) Update(ctx context.Context, id uuid.UUID, user *domain.User) (*domain.User, error) {
	ret := _m.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.User) (*domain.User, error)); ok {
		return rf(ctx, id, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.User) *domain.User); ok {
		r0 = rf(ctx, id, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.User) error); ok {
		r1 = rf(ctx, id, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - user *domain.User
func (_e *MockUserUsecase_Expecter) Update(ctx interface{}, id interface{}, user interface{}) *MockUserUsecase_Update_Call {
	return &MockUserUsecase_Update_Call{Call: _e.mock.On("Update", ctx, id, user)}
}

func (_c *MockUserUsecase_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, user *domain.User)) *MockUserUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*domain.User))
	})
	return _c
}

func (_c *MockUserUsecase_Update_Call) Return(_a0 *domain.User, _a1 error) *MockUserUsecase_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUsecase_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *domain.User) (*domain.User, error)) *MockUserUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserUsecase creates a new instance of MockUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUsecase {
	mock := &MockUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
